### ISSUE TITLE
stix to openIOC ?

### ISSUE THREAD

**Issue by cyberval** [STIXProject/openioc-to-stix#15]
Wondering if the opposite is possible ?

**Comment by gtback** [comment]
Thanks for the question, @cyberval .

STIX is a superset of OpenIOC, so there is potentially a lot of information that would be lost in the process. It's certainly possible to extract from STIX the information that's representable in OpenIOC. If I were going to do that, I would use [python-stix](https://github.com/STIXProject/python-stix) and [ioc-writer](https://github.com/mandiant/ioc_writer), but there are obviously other ways as well. 

I'm going to close this since it's not directly relevant to the openioc-to-stix script. If you have other questions, you might have some luck asking on the [cti-users mail list](https://www.oasis-open.org/committees/tc_home.php?wg_abbrev=cti#feedback), where a lot more people will see it. 

Thanks again!

**Comment by cyberval** [comment]
Thanks for the answer, what other ways were you thinking of?

**Comment by gtback** [comment]
You could read and write XML by hand (using lxml or Python's built-in XML libraries), or use languages other than Python. All I meant was that you're not forced to use python-stix and ioc-writer.
